---
# Windows E: disk Free space analysis - SQL Server datafile analysis - Ticket enrichment
- name: Check if host exists in tower inventory
  gather_facts: false
  hosts: localhost
  vars:
    HOSTS:
    SQLINSTANCE:
    DISKFREESPACETHRESHOLDPC:

  tasks:
    - block:
      - name: "Fail if Extra Variable {{ HOSTS }} does not exist in Ansible Tower's inventory"
        fail:
          msg: "{{ item }} does not exist in Ansible Tower's inventory."
        when: "item not in groups['all']"
        with_items: "{{HOSTS}}"

      rescue:
      - name: Failure to get host in tower inventory
        debug:
          msg:
            - "SYNTBOT_OUTPUT : FAILED :  This target host {{ HOSTS }} does not exist in Tower Ansible Inventory 2L22"
            - "SYNTBOT_DISPLAY : "
        failed_when: True

- name: Playbook freespace disk E
  gather_facts: false
  hosts: "{{ HOSTS }}"
  vars:
    HOSTS:
    SQLINSTANCE:
    DISKFREESPACETHRESHOLDPC:

  tasks:
    - block:
      - name: Copy ./files/freespace-e.ps1 to "{{ HOSTS }}"
        win_copy:
          src: ./files/freespace-e.ps1
          dest: C:/Temp/freespace-e.ps1
        register: result_copy

      - name: Execute Powershell C:/Temp/freespace-e.ps1 "{{ SQLINSTANCE }}" "{{ DISKFREESPACETHRESHOLDPC }}"
        win_command: powershell.exe -ExecutionPolicy ByPass -File C:/Temp/freespace-e.ps1 "{{ SQLINSTANCE }}" "{{ DISKFREESPACETHRESHOLDPC }}"
        register: result
        changed_when: false
              
      - name: Log output for SYNTBOT when successful
        debug:
          msg:
            - "SYNTBOT_OUTPUT : SUCCESSFUL on {{ HOSTS }}"
            - "SYNTBOT_DISPLAY : {{ result.stdout | replace('\r','')|replace('\n','') | trim }}"
       
      rescue:
        - name: Log output for SYNTBOT FAILED
          debug:
            msg:
              - "SYNTBOT_OUTPUT: FAILED : Task {{ ansible_failed_task.name }} failed on {{ HOSTS }} - rc {{ ansible_failed_result.rc }}"
              - "SYNTBOT_DISPLAY : {{ result.stdout | replace('\r','')|replace('\n','') | trim }}"
          failed_when: true
